### PR TITLE
Fixing ticket save issue

### LINKED ISSUE #8: Unable to save event when information other than ticket's information is changed
#**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**/**Steps to reproduce**

 - Create an event
 - Enable the ticketing system
 - Add a ticket and give it a name
 - Now save and proceed
 - Now go back to the previous wizard
 - Now change any information(say event description or create another ticket) except the ticket's information
 - And click on save and proceed

The event is not saved.

**Expected behavior:**
The event should be saved

### PR DESCRIPTION
**Pull request by invinciblycool**
Fixes #8

### CODE REVIEW

**Comment by invinciblycool** [comment]
@shubham-padia Please review.

**Comment by shubham-padia** [comment]
If the issue is due to duplicate name of the tickets, please make sure that duplicate names are not allowed. The current solution is a hack and not the ideal solution

**Comment by invinciblycool** [comment]
Sorry for the delay.
@shubham-padia I will come up with a better solution.

**Comment by mariobehling** [comment]
Issue is solved already. Thanks!

**Pull request closed without merging**
